export const CATALOGO_INICIAL = [
  {
    "id": "FB002",
    "nome": "Argola Coração",
    "categoria": "Brincos",
    "preco": 18.0,
    "imagem": "midia/Catalogo/Brinco/FB002.jpg",
    "descricao": "O clássico formato de coração com um toque moderno. Esta peça apresenta um design geométrico e clean, cheio de personalidade e estilo. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 1
  },
  {
    "id": "FB006",
    "nome": "Argola Minimalista Pequena",
    "categoria": "Brincos",
    "preco": 15.0,
    "imagem": "midia/Catalogo/Brinco/FB006.jpg",
    "descricao": "Estas argolas com fecho click possuem um design levemente mais largo (bold), garantindo conforto e um visual marcante para quem ama sobreposições. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 2
  },
  {
    "id": "FB008",
    "nome": "Argola Fio Fino",
    "categoria": "Brincos",
    "preco": 10.0,
    "imagem": "midia/Catalogo/Brinco/FB008.jpg",
    "descricao": "Aposte na leveza. Esta argola em fio delicado é perfeito para quem prefere um visual minimalista \"quase nada\", mas com o brilho na medida certa! *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 3
  },
  {
    "id": "FB010",
    "nome": "Brinco Borboleta Lace",
    "categoria": "Brincos",
    "preco": 20.0,
    "imagem": "midia/Catalogo/Brinco/FB010.jpg",
    "descricao": "Verdadeiras joias em forma de borboleta. Com um trabalho vazado que lembra renda, estes brincos são leves, femininos, autênticos e ideais para ser o destaque da sua produção. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 4
  },
  {
    "id": "FB012",
    "nome": "Brinco Mini Star",
    "categoria": "Brincos",
    "preco": 12.0,
    "imagem": "midia/Catalogo/Brinco/FB012.jpg",
    "descricao": "Um clássico indispensável para o seu porta-joias. Estes brincos em formato de estrela possuem design minimalista e acabamento polido, sendo a escolha ideal tanto para o primeiro furo quanto para compor segundos e terceiros furos. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 5
  },
  {
    "id": "FB014",
    "nome": "Brinco Orgânico Abstract",
    "categoria": "Brincos",
    "preco": 20.0,
    "imagem": "midia/Catalogo/Brinco/FB014.jpg",
    "descricao": "A tendência das formas orgânicas traduzida em acessório. Estes brincos possuem uma superfície irregular que reflete a luz de maneira única, garantindo um visual artístico, moderno e muito elegante. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 6
  },
  {
    "id": "FB017",
    "nome": "Brinco Céu Noturno",
    "categoria": "Brincos",
    "preco": 18.0,
    "imagem": "midia/Catalogo/Brinco/FB017.webp",
    "descricao": "Delicado e moderno, o Brinco Céu Noturno é perfeito para quem ama acessórios discretos e cheios de personalidade. Fabricado em aço inox, oferece excelente durabilidade, brilho e resistência ao uso diário. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 7
  },
  {
    "id": "FB018",
    "nome": "Argola Flor",
    "categoria": "Brincos",
    "preco": 18.0,
    "imagem": "midia/Catalogo/Brinco/FB018.webp",
    "descricao": "Delicado e elegante, a Argola Flor é a escolha perfeita para quem busca um acessório leve e versátil. Confeccionado em aço inox de alta qualidade, oferece excelente durabilidade, brilho e conforto para o uso diário. Seu design floral adiciona um toque de feminilidade e combina facilmente com qualquer ocasião. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 8
  },
  {
    "id": "FC001",
    "nome": "Colar Borboleta Lace",
    "categoria": "Colares",
    "preco": 28.0,
    "imagem": "midia/Catalogo/Colar/FC001.jpg",
    "descricao": "Uma peça rica em detalhes. Com um pingente de borboleta em design vazado e acabamento polido, este colar simboliza transformação com um toque de sofisticação. Ideal para ocasiões que pedem destaque. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 9
  },
  {
    "id": "FC003",
    "nome": "Colar Coração Fine Line",
    "categoria": "Colares",
    "preco": 25.0,
    "imagem": "midia/Catalogo/Colar/FC003.jpg",
    "descricao": "O clássico romântico em sua forma mais moderna. O pingente de coração vazado possui um aro fino e elegante, garantindo leveza visual e um charme atemporal que combina com qualquer look. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 10
  },
  {
    "id": "FC008",
    "nome": "Colar Lua",
    "categoria": "Colares",
    "preco": 25.0,
    "imagem": "midia/Catalogo/Colar/FC008.jpg",
    "descricao": "Delicadeza floral com brilho intenso. O pingente de flor possui pétalas com acabamento espelhado, refletindo a luz a cada movimento. Um acessório feminino que exala frescor e elegância. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 11
  },
  {
    "id": "FC010",
    "nome": "Colar Nossa Senhora",
    "categoria": "Colares",
    "preco": 30.0,
    "imagem": "midia/Catalogo/Colar/FC010.jpg",
    "descricao": "Fé e brilho em harmonia. A medalha com silhueta de Nossa Senhora é acompanhada por uma delicada pedra de zircônia, unindo proteção e o brilho clássico da joalheria fina. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 12
  },
  {
    "id": "FC011",
    "nome": "Colar Orgânico Fluido",
    "categoria": "Colares",
    "preco": 30.0,
    "imagem": "midia/Catalogo/Colar/FC011.jpg",
    "descricao": "Uma peça de design artístico e minimalista. O pingente apresenta formas curvas e orgânicas com acabamento espelhado, pendurado em uma corrente veneziana delicada. Perfeito para quem busca um acessório moderno com um toque de exclusividade. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 13
  },
  {
    "id": "FC012",
    "nome": "Colar Snake",
    "categoria": "Colares",
    "preco": 25.0,
    "imagem": "midia/Catalogo/Colar/FC012.jpg",
    "descricao": "O queridinho das composições. Com um brilho metálico contínuo e caimento impecável sobre o colo, esta corrente em malha fita é elegante, sofisticada e essencial para um visual \"clean girl\" ou para sobreposições luxuosas. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 14
  },
  {
    "id": "FC017",
    "nome": "Colar Triplo",
    "categoria": "Colares",
    "preco": 30.0,
    "imagem": "midia/Catalogo/Colar/FC017.jpg",
    "descricao": "Praticidade e estilo em uma única peça. Este colar triplo apresenta correntes em malha Singapura, conhecidas pelo seu brilho multifacetado e movimento torcido, criando um efeito de camadas perfeito. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 15
  },
  {
    "id": "FC018",
    "nome": "Colar 4 Desejos",
    "categoria": "Colares",
    "preco": 35.0,
    "imagem": "midia/Catalogo/Colar/FC018.webp",
    "descricao": "Mais do que um acessório, este colar é um símbolo de boas energias e significados especiais. Confeccionado em aço inox de alta qualidade, acompanha pingentes com os desejos de Paz, Proteção, Gentileza e Poder, tornando cada detalhe ainda mais especial. Um presente delicado e perfeito para quem acredita na beleza dos pequenos gestos. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 16
  },
  {
    "id": "FC019",
    "nome": "Colar Onda",
    "categoria": "Colares",
    "preco": 20.0,
    "imagem": "midia/Catalogo/Colar/FC019.webp",
    "descricao": "Inspirado na leveza e na liberdade do mar, o Colar Onda possui um design minimalista e elegante, perfeito para quem ama acessórios discretos e cheios de significado. Confeccionado em aço inox de alta qualidade, oferece brilho, durabilidade e resistência para acompanhar você em todos os momentos. Um clássico versátil que combina com qualquer estilo. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 17
  },
  {
    "id": "FP003",
    "nome": "Pulseira Chevron",
    "categoria": "Pulseiras",
    "preco": 25.0,
    "imagem": "midia/Catalogo/Pulseira/FP003.jpg",
    "descricao": "Moderna e sofisticada, possui elos em formato de \"V\" que criam um brilho espelhado único. Uma peça marcante que traz um ar contemporâneo ao visual. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 18
  },
  {
    "id": "FP006",
    "nome": "Pulseira Elo Português",
    "categoria": "Pulseiras",
    "preco": 25.0,
    "imagem": "midia/Catalogo/Pulseira/FP006.jpg",
    "descricao": "A base de qualquer mix de sucesso. Seus elos circulares tradicionais oferecem um acabamento limpo e brilhante, sendo a peça mais versátil da coleção. Peça masculina. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 19
  },
  {
    "id": "FP008",
    "nome": "Pulseira Zíper",
    "categoria": "Pulseiras",
    "preco": 25.0,
    "imagem": "midia/Catalogo/Pulseira/FP008.jpg",
    "descricao": "Design de elos achatados que garantem máximo conforto e reflexo de luz. Uma peça clássica que adiciona um brilho sofisticado ao pulso. Peça masculina. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 20
  },
  {
    "id": "FP014",
    "nome": "Pulseira Star",
    "categoria": "Pulseiras",
    "preco": 18.0,
    "imagem": "midia/Catalogo/Pulseira/FP014.webp",
    "descricao": "egante e delicada, a Pulseira Star é perfeita para quem ama acessórios com um toque de brilho e sofisticação. Confeccionada em aço inox de alta qualidade, oferece durabilidade, resistência e um acabamento impecável. Seu design com estrelas traz charme e versatilidade, tornando-a ideal para usar sozinha ou combinar com outras pulseiras. *selecione a quantidade desejada no carrinho!",
    "ativo": true,
    "destaque": false,
    "ordem": 21
  },
  {
    "id": "FP015",
    "nome": "Pulseira Onda",
    "categoria": "Pulseiras",
    "preco": 15.0,
    "imagem": "midia/Catalogo/Pulseira/FP015.webp",
    "descricao": "Inspirada na leveza e na tranquilidade do mar, a Pulseira Onda possui um design minimalista e atemporal que combina com qualquer estilo. Produzida em aço inox de alta qualidade, oferece brilho, resistência e durabilidade para o uso diário. Um acessório delicado e versátil, perfeito para quem valoriza elegância em cada detalhe.",
    "ativo": true,
    "destaque": false,
    "ordem": 22
  }
];
